# Generated by Django 6.1.1 on 2026-10-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_member',
            field=models.BooleanField(default=False, help_text="À activer après validation de la cotisation de l'utilisateur.", verbose_name='cotisation active'),
        ),
    ]
